name: Build and Test

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test (with coverage)
        run: |
          dotnet test "BeautyCommerce.Application.Tests/BeautyCommerce.Application.Tests.csproj" --configuration Release --no-build --collect:"XPlat Code Coverage"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults

      - name: Build Docker image
        run: |
          docker build -f BeautyCommerce.API/Dockerfile -t beautycommerce-api:latest .
