version: '3.9'

services:

  postgres:
    image: postgres:17

    container_name: beautycommerce-db

    restart: always

    environment:
      POSTGRES_DB: BeautyCommerceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: BeautyCommerce.API/Dockerfile

    container_name: beautycommerce-api

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "5000:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=BeautyCommerceDb;Username=postgres;Password=postgres

volumes:
  postgres_data:
